server {
    listen {{ openresty_port }};
    server_name {{ host_name }};

    root {{ document_root }};
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass {{ php_fpm_upstream }};
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        fastcgi_param HTTPS $https if_not_empty;
        fastcgi_param PHP_VALUE "xdebug.client_port={{ xdebug_client_port }}";
        fastcgi_read_timeout 300;
    }
}
