#!/usr/bin/env perl
use strict;
use warnings;

my $hook_type = shift @ARGV // '';
my $event = shift @ARGV // '';

if ($event eq '{{COMMAND}}:{{TIMING}}') {
    print "Хук $hook_type выполняется для команды $event.\n";
}
