meta:
  schema: task
  version: 0.1
task:
  name: Переименование проекта
  code: core.project.rename
  type: shell
  context: project
  description: Переименовывает проект и его регистрацию.
  parameters:
    code: { type: string, required: true }
  action: |
    docker-cli project:rename "$code"
