meta:
  schema: task
  version: 0.1
task:
  name: Перезапуск системных сервисов
  code: core.system.restart
  type: shell
  context: system
  description: Перезапускает один или несколько системных сервисов docker-cli.
  parameters:
    service: { type: string, required: false }
    no-rebuild-images: { type: boolean, required: false }
  action: |
    options=()
    [ -n "${service+x}" ] && options+=(--service="$service")
    [ "${no_rebuild_images:-false}" = "true" ] && options+=(--no-rebuild-images)
    docker-cli system:restart "${options[@]}"
