meta:
  schema: task
  version: 0.1
task:
  name: Удаление файлового бэкапа
  code: core.tree.backup-delete
  type: shell
  context: project
  description: Удаляет выбранный файловый бэкап проекта.
  parameters:
    backup: { name: Короткое имя бэкапа, type: string, required: true }
    location: { name: Расположение, type: string }
  action: |
    options=()
    [ -n "${location:-}" ] && options+=(--location="$location")
    docker-cli tree:backup-delete {{ backup }} "${options[@]}"
