server {
    listen {{ openresty_port }};
    server_name {{ host_name }};
{{ http_auth_config }}
    root {{ document_root }};
    index index.php index.html index.htm;

    client_max_body_size 128m;

    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt { log_not_found off; access_log off; }

    location ~* ^/(bitrix/cache|bitrix/managed_cache|bitrix/stack_cache|upload/resize_cache)/ {
        expires 30d;
        access_log off;
        try_files $uri =404;
    }

    location ~* /(?:\.ht|\.git|\.svn|composer\.(?:json|lock)|\.docker-cli\.yaml) {
        deny all;
    }

    location / {
        try_files $uri $uri/ /bitrix/urlrewrite.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /bitrix/routing_index.php =404;
        include fastcgi_params;
        fastcgi_pass {{ php_fpm_upstream }};
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        fastcgi_param HTTPS $https if_not_empty;
        fastcgi_param PHP_VALUE "xdebug.client_port={{ xdebug_client_port }}";
        fastcgi_read_timeout 300;
        fastcgi_buffer_size 32k;
        fastcgi_buffers 16 16k;
    }

    location ~* \.(?:css|js|jpg|jpeg|gif|png|webp|svg|ico|woff2?)$ {
        expires 30d;
        access_log off;
        try_files $uri =404;
    }
}
